### ISSUE TITLE
Suggestion: path regex

### ISSUE THREAD

**Issue by xav4nte** [astappiev/traefik-umami-feeder#2]
Nice plugin!
I've found that I need to be able to track requests on a regex basis. Either an includeRegex or excludeRegex option would be nice.

**Comment by astappiev** [comment]
Hi @xav4nte ,
The ability was added to [v1.2.0](https://github.com/astappiev/traefik-umami-feeder/releases/tag/v1.2.0), take a look at `ignoreURLs` configuration option, it supports regexp.
